apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
        - name: myapp
          image: europe-west3-docker.pkg.dev/sport-tournament-655af/my-docker-repo/myapp
          ports:
            - containerPort: 8080
